extends: prettier

parserOptions:
  ecmaVersion: 8
  sourceType: module

globals:
  async: true

plugins:
- prettier

env:
  browser: false
  node: true

rules:
  prettier/prettier:
  - error
  - printWidth: 120
    tabWidth: 2
    semi: false
    singleQuote: true
    trailingComma: all
    eslintIntegration: true